-- Supabase Storage Setup for Employee Photos
-- IMPORTANT: Storage policies must be created through the Supabase Dashboard, not SQL Editor
-- 
-- STEP 1: Create the bucket (via Dashboard)
-- 1. Go to Supabase Dashboard → Storage
-- 2. Click "New bucket"
-- 3. Name: employee-photos
-- 4. Public bucket: ✅ Yes (checked)
-- 5. Click "Create bucket"
--
-- STEP 2: Create policies (via Dashboard)
-- 1. Go to Storage → employee-photos → Policies tab
-- 2. Click "New Policy"
-- 3. For each policy below, create it using the Dashboard UI:
--
-- Policy 1: Read Access
--   Policy name: Allow public read access to employee photos
--   Allowed operation: SELECT
--   Target roles: public
--   USING expression: bucket_id = 'employee-photos'
--
-- Policy 2: Upload Access
--   Policy name: Allow public upload employee photos
--   Allowed operation: INSERT
--   Target roles: public
--   WITH CHECK expression: bucket_id = 'employee-photos'
--
-- Policy 3: Delete Access
--   Policy name: Allow public delete employee photos
--   Allowed operation: DELETE
--   Target roles: public
--   USING expression: bucket_id = 'employee-photos'

-- Alternative: If you want to use SQL (requires proper setup), use these statements one at a time:

-- Policy for SELECT (view/download photos)
-- CREATE POLICY "Allow public read access to employee photos" 
-- ON storage.objects 
-- FOR SELECT 
-- TO public
-- USING (bucket_id = 'employee-photos');

-- Policy for INSERT (upload photos)
-- CREATE POLICY "Allow public upload employee photos" 
-- ON storage.objects 
-- FOR INSERT 
-- TO public
-- WITH CHECK (bucket_id = 'employee-photos');

-- Policy for DELETE (remove photos)
-- CREATE POLICY "Allow public delete employee photos" 
-- ON storage.objects 
-- FOR DELETE 
-- TO public
-- USING (bucket_id = 'employee-photos');

